### ISSUE TITLE
Create Ingestion Node for Pipeline

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-node#1]
The first step in workflow automation will be to translate `external` events into the `internal` event system. 

This will be done through a `create` node that:
- receives the input Kafka Song publish event 
- filters the topic event for analysis of interest (example `sequencing_experiment` analysis only)
- define consumer type (exclusive/configurable - single or multiple consumer) 
- translates it tot he required start event on the RabbitMQ topic
- bootstrap the application 
- maybe a new repository to do this translation; simple processing lambda

**Comment by jaserud** [comment]
Created new repo with ingestion node app: https://github.com/icgc-argo/workflow-ingestion-node
