### ISSUE TITLE
Avro Generic Schemas 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-node#15]
- Schema to define queue message validation 
- mimic the implementation of schemas in edge
- determine how to load avsc schemas from class path

- when application loads, it need to read the schema for use.  need to figure out how to make this happen. 

NOTE: as part of this ticket, also investigate how we will store schemas.  In @lepsalex edge local, he is using a schema server to dl the schemas to the path.  We an also store directly with the node.. will we use this? what other options?

**Comment by andricDu** [comment]
@jaserud has added the GraphEvent schema to workflow-graph-lib
