### ISSUE TITLE
Standard Node `Complete Event` Schema 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-node#16]
- define complete schema 
- when we get a complete alert from management, enrich the data into the complete message 
- update node to execute a "complete" event in compliance with this schema and issue the complete event to the complete queue

**Comment by jaserud** [comment]
The new schema has been implemented as `GraphEvent` in workflow-graph-lib https://github.com/icgc-argo/workflow-graph-lib/blob/develop/src/main/resources/avro/GraphEvent.avsc. 

Workflow node has also been updated to make use of this schema for its input and outputs: https://github.com/icgc-argo/workflow-graph-node/pull/23, https://github.com/icgc-argo/workflow-graph-node/pull/22
