### ISSUE TITLE
Spike - Determine AMQP Software

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-node#2]
To manage the pipelines, the RDPC automation software will need its own Advanced Messaging Queue Protocol (AMPQ).  While we have been using Kafta for events, Kafka is more an enent logger than a queue manager.  We need a service that can 
- mange queues
- prioritize queues 
- is it sufficient to meet the user stories defined on wiki? and the  technical requirements of alex's workflow systems -- > ex: is there multi-consumer?

Investigate the different AMQP options and determine which will meet our needs best.

**Comment by andricDu** [comment]
@rosibaj @lepsalex if you want details:
 - Written up here: https://wiki.oicr.on.ca/display/icgcargotech/AMQP+Research
 - Settled on RabbitMQ.
