### ISSUE TITLE
Package for deploy

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-node#28]
- [ ] Jenkins file
- [ ] Docker file 
- [ ] Artifactory publish
- [ ] Helm chart/Kubernetes yamls. figure it out.
--- Configurable deploy for per-node deploy
--- Each node has its own config which determines connections, filters, etc

**Comment by andricDu** [comment]
- I had to upload graalVM images for argo here: https://hub.docker.com/repository/docker/icgcargo/graalvm
  - The one tagged with extras will allow us to perform all build related tasks as well as running the service
  - Git repo used to build: https://github.com/andricDu/graalvm-docker-image
- Fixed main class attribute: https://github.com/icgc-argo/workflow-graph-node/pull/34
- Added jenkinsfile: https://github.com/icgc-argo/workflow-graph-node/pull/35
  - Publishes docker image
  - Publishes to artifactory
  - Tags git repo

**Comment by andricDu** [comment]
We will create an rpc client for deploying graphs and reading their state. Started design work here: https://wiki.oicr.on.ca/display/icgcargotech/Graph+Authoring+Design
