### ISSUE TITLE
Update WF Node V2

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-node#8]
We have a basic create that does: 
- creates the start/completed rabbit mq queues that correspond to a registered wf
- parameter definition 
- include launcher

Now that we have the scaffold of launching a node, we need to clean up the outstanding work: 
- [x] Finish the rdpc client implementation 
---- To shepherd the wf from running to complete it needs to query wf status from management 
---- migrate wes-client to rdpc client.  Complete actions thru the graphql mutations to kick off workflows (dont talk directly with wes)

**Comment by rosibaj** [comment]
Note: mutations in dev,not qa.  may need a redeploy or restart on the gateway?

**Comment by andricDu** [comment]
wes client removed, apollo java client used to build the rdpc client with status query and mutation query.
